pipeline: rptoolkit

api:
  small_api_key: !!PLACEHOLDER!!
  large_api_key: !!PLACEHOLDER!! 
  small_base_url: https://api.deepinfra.com/v1/openai
  large_base_url: https://api.deepinfra.com/v1/openai # http://localhost:2242/v1
  small_model: deepseek-ai/DeepSeek-V3-0324
  large_model: deepseek-ai/DeepSeek-V3-0324
  small_mode: api
  large_mode: api
path:
  default_prompts: ./prompts
  input_dir: ./inputs/!!PLACEHOLDER!!
  output_dir: ./outputs/!!PLACEHOLDER!!
  prompts: ./prompts # !!ATTENTION!! by default uses normal prompts. "Spicy" prompts only compatible with the custom datagen model due to the need for vague prompts due to reputational risk.
phases:
  phase_index: 2
  work_in_phases: True
system:
  completion_mode: False
  concurrency_limit: 20
  emotions: ['DOMINANCE', 'FEARLESSNESS', 'EMBARASSMENT', 'NIHILISM',
    'DETERMINATION', 'DESPERATION', 'LOSS', 'NOSTALGIA', 'ANTICIPATION',
    'TRUST', 'FEAR', 'DISORIENTATION', 'DEGRADATION']
  include_chunk_in_prompt: True
  pick_emotion: True # whether the model generates an emotion entirely new, from the text; or picks one from the list above that fits it best
  rp_prompt_end: ''
  rp_prompt_start: ''
  use_stop: True
  subset_size: 10
  use_min_p: True
  use_subset: True # !!ATTENTION!! use subset is on; you will probably want to have use_subset on during testing and development to save money.
  chunk_size: 2000
  to_include_features: ["Initiating Event", "Character Traits", "Feelings", "Physical Traits", "Physical Props", "Overall Setting", "Settings", "Genre Tags", ] # NOTE must include genre tags or else will break
archetypes:
  generate_archetype: True # whether to generate an archetype or use a random one from the list below
  archetypes: ["THE TSUNDERE: People who embody the Tsundere archetype are defined by initial coldness, rudeness, and even violence, but eventually reveal a warmer, friendlier, possibly romantic side over time. Tsundere people are prone to embarrassed and/or flustered outbursts if approached directly by the person they like, and often have very poor control over their passionate feelings. Stories featuring tsunderes often revolve around the gradual softening of the tsundere character's attitude, and the inherent cuteness of a harsh character being shy and embarrassed as they come to terms with their feelings."] # NOTE only used with certain prompt sets. Otherwise this key will contain a meaningless, unused value.
scraping:
  use_lightnovelco: False
  lnco_base_url: https://www.lightnovelworld.co
  lnco_ranking_url: https://www.lightnovelworld.co/ranking
  lnco_chapter_count: 5
  lnco_novel_count: 5
  lnco_wait_time: 10
  lnco_max_workers: 5
cost_estimation:
  cost_per_million_small_input: 0.12
  cost_per_million_small_output: 0.30
  cost_per_million_large_input: 2.00
  cost_per_million_large_output: 6.00
meta_datagen:
  do_meta_datagen: False
  meta_datagen_keys:
    - emotion_details
    - features_details
    - scene_card_details
    - story_ratings_details
    - story_details
  meta_datagen_extras:
# That's a good point. With the cost being tracked by the engine wrapper AS THE PIPELINE EXECUTES LIVE, we have a great way to display the cost DURING THE RUN! It'll be really fun watching datasets generate while the cost and other metrics go and the graphs are there and everything, will feel fancy.